# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

   

jobs:
  build:
    name: Maven test on Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '15'
    strategy:
      matrix:
        java: ['20']
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v3

      # Set up JDK 20
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven

      # Build the project (compiles and packages the code)
      - name: Build the project
        run: mvn -B -X -e clean package --file pom.xml --batch-mode --fail-fast

      # Run tests
      - name: Run tests
        run: mvn test -B -X -e --file pom.xml --batch-mode --fail-fast
